version: '3'

services:

  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./etc/dev/nginx/nginx.crt:/etc/nginx/nginx.crt
      - ./etc/dev/nginx/nginx.key:/etc/nginx/nginx.key
      - ./etc/dev/nginx/nginx.pem:/etc/nginx/nginx.pem
      - .:/app
    depends_on:
      - php

  php:
    build: ./etc/dev/php
    volumes:
      - .:/app
    depends_on:
      - db
      - rmq

  workers:
    build: ./etc/dev/php
    volumes:
      - .:/app
    command: ['/app/bin/console', 'messenger:consume-messages', 'async']

  db:
    image: mariadb:10.4
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=gt
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=gt
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=gt
      - PMA_PASSWORD=1234

volumes:
  db_data:
